---
title: "老師帶的期末"
author: "Jason Humg"
date: "2019/6/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
library(dplyr)
library(readr)
```


```{r}
Z = read_csv("data/ta_feng_all_months_merged.csv") %>% data.frame %>% 
  setNames(c("date","cust","age","area","cat","prod","qty","cost","price"))
```

```{r}
Z$date = as.Date(Z$date, format="%m/%d/%Y")
Z$age[is.na(Z$age)] = "na"
Z$age = factor(Z$age, levels=c("<25","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64",">65","na"), labels=c("a20","a25","a30","a35","a40","a45","a50","a55","a60","a65","na")) %>% 
  as.character
Z$area = paste0("z",Z$area)
summary(Z)
```

```{r}
# Quantile of Variables
sapply(Z[,7:9], quantile, prob=c(.99, .999, .9995))
```


```{r}
# Remove Outliers
Z = subset(Z, qty<=24 & cost<=3800 & price<=4000) 
nrow(Z)  
```

```{r}
Z$tid = group_indices(Z, date, cust) # same customer same day
```


## 交易紀錄

```{r}
X = Z %>% group_by(tid) %>% 
  summarise(
    date = date[1],             # 交易日期  
    cust = cust[1],             # 顧客 ID
    age = age[1],               # 顧客 年齡級別
    area = area[1],             # 顧客 居住區別
    items = n(),                # 交易項目(總)數
    pieces = sum(qty),          # 產品(總)件數
    total = sum(price),         # 交易(總)金額
    gross = sum(price - cost)   # 毛利
  ) %>% data.frame
nrow(X) # 119422  
```
```{r}
# Check Quantile & Remove Outliers
sapply(X[,6:9], quantile, prob=c(.999, .9995, .9999))
```


```{r}
# Remove Outliers
X = subset(X, items<=62 & pieces<95 & total<16000) # 119328
```

```{r}
par(cex=0.8)
hist(X$date, "weeks", freq=T, las=2, main="No. Transaction per Week")
```

### 熱圖
```{r}
library(d3heatmap)
table(X$age, format(X$date, "%u")) %>% 
  {./rowSums(.)} %>% 
  as.data.frame.matrix() %>% 
  d3heatmap(F, F, col = "Greens")
```

